[sim]
start_time = 0 # [s] Start time of the simulation in seconds after MJD2000
dt = 10 # [s] Maximal Internal timestep used for computing charging, etc.
activity_timestep = 1 # [s] Internal timestep at which activities update, try to charge and discharge etc. 

[io]
logging_interval = 10 # [s] after how many seconds should paseos log the actor status

[power]

[comms]

[radiation]
