[sim]
start_time = 0.0 # [s] Start time of the simulation in seconds after MJD2000
dt = 10.0 # [s] Maximal Internal timestep used for computing charging, etc.
activity_timestep = 1.0 # [s] Internal timestep at which activities update, try to charge and discharge etc. 
time_multiplier = 1.0 # [unitless] Defines how much real time passes 

[io]
logging_interval = 10.0 # [s] after how many seconds should paseos log the actor status

[comm]
central_body_LOS_radius = 6371000.0 # [m] radius of the sphere blocking line of sight